/*$(function(){
    $('img#git').hover(
        function(){  
            //マウスオーバー処理
            $('img#git').css('color','RED');
        },
        function(){
            //マウスアウト処理
        }
    );
})*/